import * as tl from 'azure-pipelines-task-lib/task';
import * as fs from 'fs';
import * as path from 'path';
import { AnalysisResult } from './ai-analyzer.js';
import { TaskConfig } from './config.js';

/**
 * Formats the analysis result as Markdown, writes it to a file,
 * attaches it as a Pipeline Run Summary, and prints it to stdout.
 *
 * Handles edge cases:
 *  - Empty analysis → shows "No analysis available" message
 *  - Failed analysis → shows error report with warning
 *
 * @param analysis  Result from the AI analyzer
 * @param config    Task configuration (pipeline metadata)
 */
export async function formatAndDisplay(
    analysis: AnalysisResult,
    config: TaskConfig,
): Promise<void> {
    const timestamp = new Date().toISOString();

    // --- Build Markdown report ---
    const lines: string[] = [
        '# 🤖 Copilot Failure Analysis',
        '',
        '> 🔍 AI-powered root cause analysis for pipeline failures',
        '',
        '## 📋 Pipeline Information',
        '',
        '| Property | Value |',
        '|----------|-------|',
        `| 🔄 **Pipeline** | ${config.pipelineName} |`,
        `| 🏷️ **Build** | ${config.buildNumber} |`,
        `| 🌿 **Branch** | ${config.sourceBranch} |`,
        `| 💻 **Agent OS** | ${config.agentOS} |`,
        `| 🕐 **Analyzed** | ${timestamp} |`,
        '',
    ];

    if (analysis.success && analysis.analysisText) {
        // Successful analysis
        lines.push(
            '## 🔬 Analysis',
            '',
            analysis.analysisText,
            '',
        );
    } else if (!analysis.success) {
        // Error report
        lines.push(
            '## ⚠️ Analysis Error',
            '',
            '> ❌ The AI analysis could not be completed.',
            '',
            `**Error:** ${analysis.errorMessage ?? 'Unknown error'}`,
            '',
            `**Duration:** ${analysis.duration} ms`,
            '',
        );
    } else {
        // Empty analysis
        lines.push(
            '## 🔬 Analysis',
            '',
            '> _No analysis available. The AI model returned an empty response._',
            '',
        );
    }

    // Footer with duration and disclaimer
    lines.push(
        '---',
        '',
        `⏱️ _Analysis completed in ${(analysis.duration / 1000).toFixed(1)}s · Powered by GitHub Copilot_`,
        '',
        '> ⚠️ **Disclaimer:** This analysis is generated by AI and may not be fully accurate. '
            + 'Always verify suggestions before applying changes to your codebase.',
    );

    const markdown = lines.join('\n');

    // --- Write to file in Agent.TempDirectory ---
    const tempDir = tl.getVariable('Agent.TempDirectory') ?? '/tmp';
    const filePath = path.join(tempDir, 'copilot-analysis.md');

    try {
        fs.writeFileSync(filePath, markdown, 'utf8');
        tl.debug(`Analysis report written to ${filePath}`);

        // Attach as Pipeline Run Summary (appears in Extensions tab)
        console.log(`##vso[task.uploadsummary]${filePath}`);

        // Also upload as attachment for the custom "Copilot Failure Analysis" build results tab
        console.log(`##vso[task.addattachment type=copilot-analysis;name=report]${filePath}`);
    } catch (writeError: unknown) {
        const msg = writeError instanceof Error ? writeError.message : String(writeError);
        tl.warning(`Failed to write analysis report: ${msg}`);
    }

    // --- Print to stdout for step log visibility ---
    console.log('');
    console.log('═══════════════════════════════════════════════════════');
    console.log('  🤖  COPILOT FAILURE ANALYSIS');
    console.log('═══════════════════════════════════════════════════════');
    console.log('');

    if (analysis.success && analysis.analysisText) {
        console.log(analysis.analysisText);
    } else if (!analysis.success) {
        console.log(`⚠️  Analysis failed: ${analysis.errorMessage ?? 'Unknown error'}`);
    } else {
        console.log('No analysis available.');
    }

    console.log('');
    console.log('═══════════════════════════════════════════════════════');
}
